// <auto-generated />
using EFCore.Migrations.Toolkit.Tests.MigrationTests.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations.Toolkit.Tests.MigrationTests.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMigrationDbContext))]
    [Migration("20260426200852_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlDown:get_blog_name", "DROP PROCEDURE IF EXISTS [get_blog_name]")
                .HasAnnotation("SqlUp:get_blog_name", "CREATE OR ALTER PROCEDURE [get_blog_name] @id INT AS SELECT [Name] FROM [Blogs] WHERE [Id] = @id");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b
                        .HasAnnotation("SqlDown:trg_blog_log_changes", "DROP TRIGGER [trg_blog_log_changes];")
                        .HasAnnotation("SqlUp:trg_blog_log_changes", "CREATE OR ALTER TRIGGER [trg_blog_log_changes]\nON [Blogs]\nAFTER INSERT, UPDATE\nAS\nBEGIN\n    SET NOCOUNT ON;\n-- log blog insert or update\nEND;");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("blog_view");

                    b
                        .HasAnnotation("SqlDown:blog_view", "DROP VIEW IF EXISTS blog_view")
                        .HasAnnotation("SqlUp:blog_view", "CREATE VIEW blog_view AS SELECT * FROM [Blogs]");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostBase");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b
                        .HasAnnotation("SqlDown:trg_order_prevent_negative_amount", "DROP TRIGGER [trg_order_prevent_negative_amount];")
                        .HasAnnotation("SqlDown:trg_order_set_confirmed", "DROP TRIGGER [trg_order_set_confirmed];")
                        .HasAnnotation("SqlUp:trg_order_prevent_negative_amount", "CREATE OR ALTER TRIGGER [trg_order_prevent_negative_amount]\nON [Orders]\nAFTER UPDATE\nAS\nBEGIN\n    SET NOCOUNT ON;\nIF EXISTS (SELECT 1 FROM inserted WHERE [TotalAmount] < 0)\n    THROW 50001, 'Amount must not be negative', 1;\nEND;")
                        .HasAnnotation("SqlUp:trg_order_set_confirmed", "CREATE OR ALTER TRIGGER [trg_order_set_confirmed]\nON [Orders]\nAFTER INSERT\nAS\nBEGIN\n    SET NOCOUNT ON;\nUPDATE [Orders] SET [IsConfirmed] = 0 WHERE [Id] IN (SELECT [Id] FROM inserted)\nEND;");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PostB");
                });
#pragma warning restore 612, 618
        }
    }
}
