// <auto-generated />
using EFCore.Migrations.Toolkit.Sample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.Migrations.Toolkit.Sample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("SqlDown:get_author_name", "DROP FUNCTION IF EXISTS get_author_name(integer)")
                .HasAnnotation("SqlDown:published_posts_view", "DROP VIEW IF EXISTS published_posts_view")
                .HasAnnotation("SqlUp:get_author_name", "CREATE OR REPLACE FUNCTION get_author_name(author_id integer)\nRETURNS text\nLANGUAGE sql STABLE AS $$\n    SELECT \"Name\" FROM \"Authors\" WHERE \"Id\" = author_id;\n$$")
                .HasAnnotation("SqlUp:published_posts_view", "CREATE OR REPLACE VIEW published_posts_view AS\nSELECT p.\"Id\", p.\"Title\", p.\"AuthorId\"\nFROM \"Posts\" p\nWHERE p.\"Status\" = 1");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Sample.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор автора.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Email автора.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Имя автора.");

                    b.HasKey("Id");

                    b.ToTable("Authors", t =>
                        {
                            t.HasComment("Автор публикаций.");
                        });
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Sample.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор публикации.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasComment("Идентификатор автора.");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Содержимое публикации.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Статус публикации.\n\n0 - Черновик, не опубликован.\n1 - Опубликован и доступен читателям.\n2 - Архивирован, скрыт от читателей.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Заголовок публикации.");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts", t =>
                        {
                            t.HasComment("Публикация в блоге.");
                        });

                    b
                        .HasAnnotation("SqlDown:audit_post_insert", "DROP FUNCTION audit_post_insert() CASCADE;")
                        .HasAnnotation("SqlDown:prevent_direct_archive", "DROP FUNCTION prevent_direct_archive() CASCADE;")
                        .HasAnnotation("SqlDown:set_post_status_on_insert", "DROP FUNCTION set_post_status_on_insert() CASCADE;")
                        .HasAnnotation("SqlUp:audit_post_insert", "CREATE FUNCTION audit_post_insert() RETURNS trigger as $audit_post_insert$\r\nBEGIN\r\nRAISE NOTICE 'Post inserted: %', NEW.\"Id\";\r\nRETURN NEW;\r\nEND;\r\n$audit_post_insert$ LANGUAGE plpgsql;\r\n\r\nCREATE CONSTRAINT TRIGGER audit_post_insert AFTER INSERT\r\nON \"Posts\"\r\nDEFERRABLE INITIALLY DEFERRED\r\nFOR EACH ROW EXECUTE PROCEDURE audit_post_insert();\r\n")
                        .HasAnnotation("SqlUp:prevent_direct_archive", "CREATE FUNCTION prevent_direct_archive() RETURNS trigger as $prevent_direct_archive$\r\nBEGIN\r\nIF NEW.\"Status\" = 2 AND OLD.\"Status\" = 1 THEN\n    RAISE EXCEPTION 'Use dedicated archive procedure instead of direct UPDATE';\nEND IF;\r\nRETURN NEW;\r\nEND;\r\n$prevent_direct_archive$ LANGUAGE plpgsql;\r\n\r\nCREATE TRIGGER prevent_direct_archive BEFORE UPDATE\r\nON \"Posts\"\r\nFOR EACH ROW EXECUTE PROCEDURE prevent_direct_archive();\r\n")
                        .HasAnnotation("SqlUp:set_post_status_on_insert", "CREATE FUNCTION set_post_status_on_insert() RETURNS trigger as $set_post_status_on_insert$\r\nBEGIN\r\nNEW.\"Status\" = 0;\r\nRETURN NEW;\r\nEND;\r\n$set_post_status_on_insert$ LANGUAGE plpgsql;\r\n\r\nCREATE TRIGGER set_post_status_on_insert BEFORE INSERT\r\nON \"Posts\"\r\nFOR EACH ROW EXECUTE PROCEDURE set_post_status_on_insert();\r\n");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Sample.Models.Post", b =>
                {
                    b.HasOne("EFCore.Migrations.Toolkit.Sample.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Sample.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
