// <auto-generated />
using EFCore.Migrations.Toolkit.Tests.MigrationTests.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.Migrations.Toolkit.Tests.MigrationTests.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlMigrationDbContext))]
    partial class PostgreSqlMigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("SqlDown:blog_names", "DROP VIEW IF EXISTS public.blog_names")
                .HasAnnotation("SqlDown:get_blog_name", "DROP FUNCTION IF EXISTS GetName")
                .HasAnnotation("SqlUp:blog_names", "CREATE OR REPLACE VIEW public.blog_names\nAS SELECT \"Id\", \"Name\" FROM \"Blogs\"")
                .HasAnnotation("SqlUp:get_blog_name", "CREATE OR REPLACE FUNCTION GetName(id integer)\nRETURNS text AS $$\nBEGIN\nRETURN (SELECT \"Name\" FROM \"Blogs\" WHERE \"Id\" = id);\n END;\n$$ LANGUAGE plpgsql;");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор блога.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasComment("Название блога.");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasComment("URL блога.");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b
                        .HasComment("Блог.")
                        .HasAnnotation("SqlDown:before_insert_or_update_blog", "DROP FUNCTION before_insert_or_update_blog() CASCADE;")
                        .HasAnnotation("SqlUp:before_insert_or_update_blog", "CREATE FUNCTION before_insert_or_update_blog() RETURNS trigger as $before_insert_or_update_blog$\nBEGIN\nIF NEW.\"Url\" IS NOT NULL AND NEW.\"Url\" IS DISTINCT FROM OLD.\"Url\" THEN\n    RAISE EXCEPTION 'Нельзя менять URL';\nEND IF;\nIF NEW.\"Name\" IS NOT NULL THEN\n    UPDATE \"Blogs\" SET \"Url\" = NEW.\"Url\"\n    WHERE \"Name\" = NEW.\"Name\";\nEND IF;\nRETURN NEW;\nEND;\n$before_insert_or_update_blog$ LANGUAGE plpgsql;\n\nCREATE TRIGGER before_insert_or_update_blog BEFORE INSERT OR UPDATE\nON \"Blogs\"\nFOR EACH ROW EXECUTE PROCEDURE before_insert_or_update_blog();");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.BlogView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.ToView("blog_view");

                    b
                        .HasAnnotation("SqlDown:blog_view", "DROP VIEW IF EXISTS blog_view")
                        .HasAnnotation("SqlUp:blog_view", "CREATE VIEW blog_view AS SELECT * FROM \"Blogs\"");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PostBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostBase");

                    b.HasComment("Базовый тип в наследовании TPH.");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Идентификатор заказа.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("Категория заказа.\n\n0 - Одежда.\n1 - Книги.\n2 - Игрушки.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer")
                        .HasComment("Способ доставки.");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasComment("Статус подтверждения заказа.");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasComment("Номер заказа.");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Статус заказа.\n\n0 - Активный, ожидает выполнения.\n1 - Выполнен, доставлен покупателю.\n2 - Отменён, возврат средств.")
                        .HasAnnotation("AutoCommentEnumDescription", "");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasComment("Итоговая сумма заказа в рублях.");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b
                        .HasComment("Заказ покупателя.")
                        .HasAnnotation("SqlDown:prevent_update_negative_amount", "DROP FUNCTION prevent_update_negative_amount() CASCADE;")
                        .HasAnnotation("SqlDown:set_order_defaults", "DROP FUNCTION set_order_defaults() CASCADE;")
                        .HasAnnotation("SqlUp:prevent_update_negative_amount", "CREATE FUNCTION prevent_update_negative_amount() RETURNS trigger as $prevent_update_negative_amount$\nBEGIN\nIF NEW.total_amount < 0 THEN RAISE EXCEPTION 'amount negative'; END IF;\nRETURN NEW;\nEND;\n$prevent_update_negative_amount$ LANGUAGE plpgsql;\n\nCREATE TRIGGER prevent_update_negative_amount BEFORE UPDATE\nON \"Orders\"\nFOR EACH ROW EXECUTE PROCEDURE prevent_update_negative_amount();")
                        .HasAnnotation("SqlUp:set_order_defaults", "CREATE FUNCTION set_order_defaults() RETURNS trigger as $set_order_defaults$\nBEGIN\nNEW.is_confirmed = false;\nRETURN NEW;\nEND;\n$set_order_defaults$ LANGUAGE plpgsql;\n\nCREATE TRIGGER set_order_defaults BEFORE INSERT\nON \"Orders\"\nFOR EACH ROW EXECUTE PROCEDURE set_order_defaults();");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostA", b =>
                {
                    b.HasBaseType("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextA")
                        .HasColumnType("text")
                        .HasComment("Текст А.");

                    b.HasDiscriminator().HasValue("PostA");
                });

            modelBuilder.Entity("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostB", b =>
                {
                    b.HasBaseType("EFCore.Migrations.Toolkit.Tests.Models.Inheritance.PostBase");

                    b.Property<string>("TextB")
                        .HasColumnType("text")
                        .HasComment("Текст Б.");

                    b.HasDiscriminator().HasValue("PostB");
                });
#pragma warning restore 612, 618
        }
    }
}
