name: Push Nuget Packages

on:
  push:
    branches: [ "net-5" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: EFCore.Migrations.Toolkit.Tests
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ComplexPassword123!
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'ComplexPassword123!' -C -Q 'SELECT 1' -b -o /dev/null"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ConnectionStrings__PostgreSqlTestDatabase: "Host=localhost;Port=5432;Database=EFCore.Migrations.Toolkit.Tests;Username=postgres;Password=postgres"
      ConnectionStrings__SqlServerTestDatabase: "Server=localhost,1433;Database=EFCore.Migrations.Toolkit.Tests;User Id=sa;Password=ComplexPassword123!;"

    steps:
    - uses: actions/checkout@v4
    - name: Install libssl1.1
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -f net5.0 -c Release --no-build --no-restore

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libssl1.1
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack -c Release --output nuget-packages
    - name: Push nuget packages
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
